### ISSUE TITLE
Delete given node in a Linked List

### ISSUE THREAD

**Issue by shanvijha30** [csubhasundar/CodingPractice-Hacktoberfest23#104]
Write a function to delete a node in a singly-linked list. You will not be given access to the head of the list instead, you will be given access to the node to be deleted directly. It is guaranteed that the node to be deleted is not a tail node in the list.

Language : java

**Comment by shanvijha30** [comment]
@csubhasundar Please assign this issue to me. I would like to work on it.

**Comment by Wafmulla** [comment]
Hello, Can you please assign this task to me?

**Comment by jiteshh-10** [comment]
Kindly assign the issue to me for resolution.
