### ISSUE TITLE
Merge two sorted Linked Lists

### ISSUE THREAD

**Issue by shanvijha30** [csubhasundar/CodingPractice-Hacktoberfest23#105]
Given two singly linked lists that are sorted in increasing order of node values, merge two sorted linked lists and return them as a sorted list. The list should be made by splicing together the nodes of the first two lists.

**Comment by shanvijha30** [comment]
@csubhasundar Please assign this issue to me under Hacktoberefest 2023. I would like to work on it.

**Comment by vilasrhegde** [comment]
Please assign me. I  will use Python to solve this one

**Comment by Wafmulla** [comment]
I can use c++ to solve this issue.
Can you please assign this issue to me under Habtoberfest 2023 label?

**Comment by aayushii9602** [comment]
Can i contribute to this?, you can check my [profile](https://leetcode.com/aayushii09/)

**Comment by jiteshh-10** [comment]
Kindly assign the issue to me for resolution.

**Comment by sujal1256** [comment]
Kindly assign me this issue I can solve this. I already have an approach I can make a new list while going through both the lists and adding nodes to the new list  in a sorted way.

**Comment by divya1515** [comment]
please assign me this issue

**Comment by amishah1110** [comment]
kindly assign me this
