### ISSUE TITLE
Binary Search

### ISSUE THREAD

**Issue by tanisha91** [csubhasundar/CodingPractice-Hacktoberfest23#111]
please Assign it to me

**Comment by Amisha328** [comment]
Hi @csubhasundar,

Please review and accept the PR #118 

Thank you !! :)

**Comment by Ishika0-0** [comment]
@csubhasundar Can I contribute to #111 issue

**Comment by devvkumar** [comment]
please assign this #111 task to me.

**Comment by anushkp1107** [comment]
@csubhasundar can I contribute to #111 issue under hacktoberfest 2023?

**Comment by Carnival02** [comment]
Hello @csubhasundar
I am practicing DSA since last 2 months and I would like to contribute in this #111 issue so can you assign it to me

**Comment by Wafmulla** [comment]
Can you please assign this issue to me under the label Hacktoberfest 2023?

**Comment by rehan700** [comment]
Hello @Midway91, please assign this issue to me under HACKTOBERFEST2023

This will be my first issue.





















I need it very badly

**Comment by gulatikeshav** [comment]
@csubhasundar  please assign this issue to me

**Comment by PreethamShastry** [comment]
@csubhasundar please assign it to me
