### ISSUE TITLE
Quick Sort Algorithm using Java

### ISSUE THREAD

**Issue by EshaalakshmiDS** [csubhasundar/CodingPractice-Hacktoberfest23#229]
Hi,
I would like to implement Quick Sort Algorithm in Java and C++ Under Hactoberfest_2023 if you like please assign me this.
Thanks & Happy Coding @csubhasundar

**Comment by PreethamShastry** [comment]
@csubhasundar please assign to me

**Comment by AdityaShaw1** [comment]
pls assign me this issue

**Comment by RekhaNPatil** [comment]
Hello , i would like to solve this problem please can you assign it to me
