### ISSUE TITLE
Binary Search Algo in C++

### ISSUE THREAD

**Issue by th-shristi** [csubhasundar/CodingPractice-Hacktoberfest23#52]
@csubhasundar Can I work on this under hacktoberfest2023 label?

**Comment by abhinavtyagi88** [comment]
#include <iostream>
#include <vector>

int binarySearch(const std::vector<int>& arr, int target) {
    int left = 0;
    int right = arr.size() - 1;
    
    while (left <= right) {
        int mid = left + (right - left) / 2;
        
        // Check if the target is present at the middle
        if (arr[mid] == target) {
            return mid;
        }
        
        // If the target is greater, ignore left half
        else if (arr[mid] < target) {
            left = mid + 1;
        }
        
        // If the target is smaller, ignore right half
        else {
            right = mid - 1;
        }
    }
    
    // Target was not found in the array
    return -1;
}

int main() {
    std::vector<int> arr = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
    int target = 6;
    int result = binarySearch(arr, target);
    
    if (result != -1) {
        std::cout << "Element found at index: " << result << std::endl;
    } else {
        std::cout << "Element not found in the array." << std::endl;
    }
    
    return 0;
}
